### ISSUE TITLE
Microsoft.AspNet.HttpOverrides.Tests test failures on CoreCLR on Linux

### ISSUE THREAD

**Issue by cesarbs** [aspnet/BasicMiddleware#15]
info: Exec
    info:   program: /usr/bin/env
    info:   commandline: bash -c ". \"/home/cesars/src/aspnet/universe/BasicMiddleware/packages/KoreBuild/build/dnvm.sh\"; dnvm run default -runtime coreclr test"
    info:   workingdir: test/Microsoft.AspNet.HttpOverrides.Tests
    xUnit.net DNX Runner (64-bit DNXCore 5.0)
      Discovering: Microsoft.AspNet.HttpOverrides.Tests
      Discovered:  Microsoft.AspNet.HttpOverrides.Tests
      Starting:    Microsoft.AspNet.HttpOverrides.Tests
          Assert.Equal() Failure
                        ↓ (pos 4)
          Expected: testHost
          Actual:   testhost
                        ↑ (pos 4)
          Stack Trace:
               at Microsoft.AspNet.HttpOverrides.OverrideMiddlewareHeaderTests.<>c__DisplayClass2_0.<XForwardedHostOverrideChangesRequestHost>b__1(HttpContext context)
               at Microsoft.AspNet.HttpOverrides.OverrideHeaderMiddleware.Invoke(HttpContext context)
               at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.HttpOverrides.OverrideMiddlewareHeaderTests.<XForwardedHostOverrideChangesRequestHost>d__2.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
          Assert.Equal() Failure
                        ↓ (pos 4)
          Expected: testHost
          Actual:   testhost
                        ↑ (pos 4)
          Stack Trace:
               at Microsoft.AspNet.HttpOverrides.OverrideMiddlewareHeaderTests.<>c__DisplayClass5_0.<AllForwardsEnabledChangeRequestRemoteIpHostandProtocol>b__1(HttpContext context)
               at Microsoft.AspNet.HttpOverrides.OverrideHeaderMiddleware.Invoke(HttpContext context)
               at Microsoft.AspNet.Hosting.Internal.RequestServicesContainerMiddleware.<Invoke>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.Hosting.Internal.HostingEngine.<>c__DisplayClass32_0.<<Start>b__0>d.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.TestHost.ClientHandler.<>c__DisplayClass3_0.<<SendAsync>b__0>d.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at Microsoft.AspNet.TestHost.ClientHandler.<SendAsync>d__3.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
               at Microsoft.AspNet.HttpOverrides.OverrideMiddlewareHeaderTests.<AllForwardsEnabledChangeRequestRemoteIpHostandProtocol>d__5.MoveNext()
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
            --- End of stack trace from previous location where exception was thrown ---
               at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
               at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
      Finished:    Microsoft.AspNet.HttpOverrides.Tests
    === TEST EXECUTION SUMMARY ===
       Microsoft.AspNet.HttpOverrides.Tests  Total: 11, Errors: 0, Failed: 2, Skipped: 0, Time: 0.708s

**Comment by cesarbs** [comment]
This affects https://github.com/aspnet/Universe/issues/304.

**Comment by muratg** [comment]
@cesarbs Could you lowercase this in the testhost? (i.e. instead of `testHost` it should be `testhost`) This way it'll pass on both CLRs.
